#Indigo properties file
#Sun Jul 19 17:21:53 ART 2026
always-tesselate-blocks=auto
ambient-occlusion-mode=hybrid
debug-compare-lighting=auto
fix-exterior-vertex-lighting=auto
fix-luminous-block-ambient-occlusion=auto
fix-smooth-lighting-offset=auto
